config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'home#show'

  root to: 'home#show'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :weather
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :city
  belongs_to :user

  validates :note, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  def self.update_or_create(auth)
    user = User.find_by(uid: auth[:uid]) || User.new
    user.attributes = {
      provider: auth[:provider],
      uid: auth[:uid],
      email: auth[:info][:email],
      first_name: auth[:info][:first_name],
      last_name: auth[:info][:last_name]
    }
    user.save!
    user
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  has_one :city

  validates_presence_of :temperature
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?

  def authenticate
    redirect_to :login unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show
    return unless user_signed_in?

    @name = current_user.first_name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate
  before_action :find_post, only: %i[edit update destroy]

  def index
    @form = CreatePostForm.new
    posts
  end

  def create
    temperature = WeatherFinder.new(params[:create_post_form][:city_name]).call
    @form = CreatePostForm.new(post_params.merge(temperature: temperature))

    if @form.save
      redirect_to posts_path, notice: 'Post successfully created'
    else
      posts
      render action: :index, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(edit_params)
      redirect_to posts_path, notice: 'Post successfully updated'
    else
      render action: :edit
    end
  end

  def destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to posts_path, notice: 'User was successfully destroy.' }
        format.js
      else
        posts
        format.html { render action: :index }
      end
    end
  end

  private

  def post_params
    params.require(:create_post_form).permit(:note, :city_name).merge(user_id: current_user.id)
  end

  def edit_params
    params.require(:post).permit(:note)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def posts
    @posts = current_user.posts.includes(:city, city: :weather).order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    @user = User.update_or_create(request.env['omniauth.auth'])
    session[:user_id] = @user.id
    redirect_to :posts, notice: "Welcome #{@user.first_name}!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Successful logout'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/show.html.erb
<div class="jumbotron col-md-6 offset-md-3" align="center">
  <% if user_signed_in? %>
    <h1>Welcome <%= @name %> !</h1>
  <% else %>
    <h1>Welcome traveller!</h1>
  <% end %>
  <% if user_signed_in? %>
    <h2>Add post to your journal</h2>
    <div class="margin">
      <%= link_to 'Your journal', posts_path, class: 'btn btn-info' %>
    </div>
  <% else %>
    <h2>Please login to continue</h2>
    <div class="margin">
      <%= link_to 'Sign in with Google', login_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item <%= 'active' if current_page?(home_path) %>">
            <a class="nav-link" href= <%= home_path %> >Home</a>
          </li>
          <li class="nav-item <%= 'active' if current_page?(posts_path) %>">
            <a class="nav-link" href= <%= posts_path %> >Posts</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <form>
            <% if user_signed_in? %>
              <strong class="text-light"><%= "Logged in as: " + current_user.email %></strong>
              <span class="text-light">|</span>
              <%= link_to "Logout", logout_path, class: 'navbar-link text-secondary' %>
            <% else %>
              <%= link_to "Login", login_path, class: 'navbar-link text-secondary' %>
            <% end %>
          </form>
        </ul>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-6 offset-md-3 margin">
  <h2>Edit your post</h2>

  <%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.text_area :note, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= form_for @form, url: posts_path do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="col-md-6 offset-md-3 margin">
    <h2>Create Post</h2>
    <div class="form-group">
      <%= f.text_field :city_name, placeholder: 'City', class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.text_area :note, placeholder: 'Note', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

<div class="col-md-6 offset-md-3">
  <h2>Older posts</h2>
  <table class="table">
    <% @posts.each do |post| %>
      <tbody>
        <tr class="table-header">
          <th class="table-title">
            <%= post.created_at.strftime("%d-%m-%Y") %>
            <%= post.city.name %>
            <%= post.city.weather.temperature %>&#176C
          </th>
          <th class="btn-edit">
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-outline-success btn-sm' %>
            <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-outline-danger btn-sm js-delete-link' %>
          </th>
        </tr>
        <tr class="truncate">
          <td colspan="2">
            <a class="text-truncate"><%= post.note %></a>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The post contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>